#!/usr/bin/env bash

## Description: Run wyvr inside the web container.
## Usage: wyvr
## Example: "ddev wyvr" or with additional arguments such as "ddev wyvr dev"

DEBUG=""

for var in "$@"; do
    if [[ "$var" == "--inspect" ]]; then
        DEBUG="--inspect-brk=0.0.0.0"
    fi
done

NODE=$(find $HOME/.nvm/versions/node/**/bin -name "node" | tail -1)

if [[ -n "$DEBUG" ]]; then
    echo -e "\e[32mNode.js debugging active\e[0m"
fi

if [[ -z "$NODE" ]]; then
    echo -e "\e[31mNo Node.js found\e[0m"
    exit 1;
fi

$NODE $DEBUG ./node_modules/\@wyvr/generator/bin/index.js $@
