/* App.svelte generated by Svelte v3.55.1 */
import { create_ssr_component, each, validate_component } from "svelte/internal";

import Thing from './Thing.svelte';

const App = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let things = [
		{ id: 1, name: 'apple' },
		{ id: 2, name: 'banana' },
		{ id: 3, name: 'carrot' },
		{ id: 4, name: 'doughnut' },
		{ id: 5, name: 'egg' }
	];

	function handleClick() {
		things = things.slice(1);
	}

	return `<button>Remove first thing
</button>

${each(things, thing => {
		return `${validate_component(Thing, "Thing").$$render($$result, { name: thing.name }, {}, {})}`;
	})}`;
});

export default App;