/* generated by Svelte v3.58.0 */
import { add_attribute, create_ssr_component } from 'svelte/internal';

import { onMount } from 'svelte';

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	wyvr: {
		render: 'hydrate';
		loading: 'lazy';
	}

	let { product } = $$props;
	let slot_product;

	onServer(() => {
		slot_product = product;
	});

	onMount(() => {
		slot_product = product;

		on('shop-product-switch', switch_product => {
			console.log(switch_product, product);
		});
	});

	if ($$props.product === void 0 && $$bindings.product && product !== void 0) $$bindings.product(product);

	return `<div data-hydrate="magento2_product_Switcher" data-hydrate-path="$src/magento2/product/Switcher.svelte"${add_attribute("data-props", _prop('product', product), 0)}><div><span data-slot="product">${slots.product
	? slots.product({ product: slot_product })
	: ``}</span></div></div>`;
});

export default Component;